### PR TITLE
chore: update CODEOWNERS Add Maya

### PR DESCRIPTION
**Pull request by Mayaleeeee**
Add Maya to the AsyncAPI Brand repo.

resolves https://github.com/asyncapi/brand/issues/102

### CODE REVIEW

**Comment by Mayaleeeee** [comment]
Hey, @derberg, please take a look at this.

**Comment by derberg** [comment]
@fmvilas whenever you have a moment, please have a look. Missy is ok with the change

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Pull request merged**
