### PR TITLE
feat: add marketing and social media design to areas if contributions

### PR DESCRIPTION
**Pull request by mcturco**
As per @derberg's suggestion in the "Let's talk about contributing" live stream, a line was added in the README to show that you can also contribute to marketing/social media design requests.

### CODE REVIEW

**Review by alequetzalli — APPROVED** [review]
LGTM 🚀

**Comment by alequetzalli** [comment]
But since this is the brand repo, you actually need a review approval from @fmvilas to get it merged 😃

**Review by fmvilas — APPROVED** [review]
:shipit:

**Comment by mcturco** [comment]
@alequetzalli @fmvilas Thank you guys!

**Pull request merged**
